server:
  port: 8910
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_spiral_ai
    username: huhailong
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: spiral-ai-manager
api-key:
  deepseek: ${deepseekAPIKey}
app:
  jwt:
    secret: 63c99adb95c1e216dd0014cdd86ecab9 # md5: spiral-ai-manager-secret
    expirationMs: 604800000 # 7 days in milliseconds
  cors:
    allowed-origins:
      - http://localhost:3000
#logging:
#  level:
#    com.zaxxer.hikari: debug